---
- hosts: webservers
  remote_user: jenkins
  tasks:
  - name: Fetch App config files ...
    shell: cd /AppConfig && git fetch && git merge origin/master
     
  - name: Remove Cloud config service container ...
    shell: docker rm -f cloud.config.service

  - name: Pull Cloud config service image ...
    shell: docker pull 10.39.101.226:5000/cloud.config.service

  - name: Run Cloud config service containers...
    shell: docker run -d --name cloud.config.service -p 7080:8080 -e CONFIG.SERVER.AUTH.CODE=AUTHCODE-0001 -e SERVICE_NAME=cloud.config.service -e SERVICE_TAGS=test10.39.101.226:5000/cloud.config.service

 