---
- hosts: webservers
  remote_user: jenkins
  tasks:
     
  - name: Remove Cloud config service container ...
    shell: docker rm -f cloud.config.service
    ignore_errors: yes

  - name: Remove Cloud config service image ...
    shell: docker rmi -f 10.39.101.226:5000/cloud.config.service
    ignore_errors: yes
 
  - name: Pull Cloud config service image ...
    shell: docker pull 10.39.101.226:5000/cloud.config.service

  - name: Run Cloud config service containers...
    shell: docker run -d -v /AppConfig/test:/AppConfig/test --name cloud.config.service -p 7080:8080 -e CLOUD.CONFIG.SERVICE.AUTH.CODE=config.auth.code:001 -e SERVICE_NAME=cloud.config.service -e SERVICE_TAGS=test 10.39.101.226:5000/cloud.config.service

 